export type HighlightColor = 'yellow' | 'red' | 'green' | 'blue';

export interface Highlight {
  id: string;
  type: 'text' | 'image';
  text: string;
  imageUrl?: string;
  color: HighlightColor;
  createdAt: number;
  pos?: number;
  startPath?: number[];
  startOffset?: number;
  endPath?: number[];
  endOffset?: number;
}

export interface NoteData {
  url: string;
  title: string;
  author?: string;
  sourceName?: string;
  highlights: Highlight[];
  createdAt: number;
}

export const generateMarkdown = (note: NoteData): string => {
  const date = new Date(note.createdAt).toLocaleDateString();
  const ordered = [...note.highlights].sort((a, b) => {
    const ap = a.pos ?? a.createdAt;
    const bp = b.pos ?? b.createdAt;
    return ap - bp;
  });
  const highlightsMd = ordered
    .map(h => {
      if (h.type === 'image') return `![${h.text}](${h.imageUrl})`;
      return `- ${h.text}`;
    })
    .join('\n\n');

  return `# ${note.title}
> Source: [${note.author || 'Unknown'}](${note.url})
> Date: ${date}

## Highlights
${highlightsMd}

---
Generated by FlowRead`;
};
