
export type HighlightColor = 'yellow' | 'red' | 'green' | 'blue';

export interface Highlight {
  id: string;
  type: 'text' | 'image';
  text: string; // 对于图片，存储 alt 文本
  imageUrl?: string; // 仅对图片有效
  color: HighlightColor;
  createdAt: number;
  pos?: number;
  // 文本高亮的稳定锚点：基于全文字符偏移，便于重渲染/重开后恢复
  startOffset?: number;
  endOffset?: number;
}

export interface NoteData {
  url: string;
  title: string;
  author?: string;
  sourceName?: string;
  highlights: Highlight[];
  createdAt: number;
}

// 保存笔记数据
export const saveNote = async (note: NoteData): Promise<void> => {
  const key = `note_${note.url}`;
  try {
    await chrome.storage.local.set({ [key]: note });
  } catch (error) {
    console.error('Failed to save note:', error);
    throw error;
  }
};

// 获取笔记数据
export const getNote = async (url: string): Promise<NoteData | null> => {
  const key = `note_${url}`;
  const result = await chrome.storage.local.get(key);
  return result[key] || null;
};

// 生成 Markdown
export const generateMarkdown = (note: NoteData): string => {
  const date = new Date(note.createdAt).toLocaleDateString();
  const ordered = [...note.highlights].sort((a, b) => {
    const ap = a.pos ?? a.createdAt;
    const bp = b.pos ?? b.createdAt;
    return ap - bp;
  });
  const highlightsMd = ordered
    .map(h => {
      if (h.type === 'image') {
        return `![${h.text}](${h.imageUrl})`;
      }
      return `- ${h.text}`;
    })
    .join('\n\n');

  return `# ${note.title}
> Source: [${note.author || 'Unknown'}](${note.url})
> Date: ${date}

## Highlights
${highlightsMd}

---
Generated by FlowRead`;
};
